CREATE TABLE IF NOT EXISTS integracion_configuracion (
    clave VARCHAR(100) NOT NULL PRIMARY KEY,
    valor LONGTEXT NOT NULL,
    es_secreto TINYINT(1) NOT NULL DEFAULT 0,
    actualizado_por VARCHAR(150) NULL,
    actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
